### ISSUE TITLE
Works but seems not be using mbps and is using kbps 

### ISSUE THREAD

**Issue by TATUMTOT** [irsheep/MMM-SnmpIntSpeed#2]
how do I change it to mbps it is pulling the data but will MAX out the gauge. My device that I’m pulling from is a SOPHOS UTM. I can try it from PFsense but main FW is the UTM.

Thanks

**Comment by irsheep** [comment]
Hi,

Can you edit the GetInterfaces.js file and replace code on line 8

`const oid2mib = {
  '1.3.6.1.2.1.2.2.1.2': 'ifDescr',
  '1.3.6.1.2.1.31.1.1.1.1': 'ifName',
  '1.3.6.1.2.1.31.1.1.1.18': 'ifAlias'
}`

With

`const oid2mib = {
    '1.3.6.1.2.1.2.2.1.2': 'ifDescr',
    '1.3.6.1.2.1.31.1.1.1.1': 'ifName',
    '1.3.6.1.2.1.31.1.1.1.18': 'ifAlias',
    '1.3.6.1.2.1.2.2.1.5': 'ifSpeed',
    '1.3.6.1.2.1.31.1.1.1.15': 'ifHighSpeed',
    '1.3.6.1.2.1.31.1.1.1.6': 'ifHCInOctets',
    '1.3.6.1.2.1.31.1.1.1.10': 'ifHCOutOctets'
}
`
Then run 
`node GetInterfaces.js --version 2 --community public --host 127.0.0.1`
and post the output, don't forget to change the community and host.

**Comment by TATUMTOT** [comment]
@irsheep Thanks i will give that a Try.
