### ISSUE TITLE
Set Interface Speed

### ISSUE THREAD

**Issue by ebowcock** [irsheep/MMM-SnmpIntSpeed#5]
Is there a way to hard code the gauges to what their maximum speed is? It's working correctly, but if I'm monitoring a 100 Mbps internet connection on a 1 Gbps gauge it doesn't really show well.

**Comment by irsheep** [comment]
Hi, just uploaded a new version that allows you to define the interface speed. Check the **speed** setting in the  README.

**Comment by ebowcock** [comment]
Update works great. Thank you for the addition!
